### ISSUE TITLE
Sequel support

### ISSUE THREAD

**Issue by pabloh** [nepalez/rspec-sqlimit#1]
This is a extremely nice project. It would be nice if we could use it outside AR, have you consider adding Sequel support?.

**Comment by nepalez** [comment]
Thank you! For now I don't have a good idea of how to count queries in sequel outside of Rails and its pub/sub system I've mentioned in a blog. I think this could be made for sequel in Raills, but I wonder if this is useful (I mean why use Rails w/o ActiveRecord?)
