### ISSUE TITLE
Cut new release that contains Rails 6 friendly commits

### ISSUE THREAD

**Issue by jaysonvirissimo** [nepalez/rspec-sqlimit#13]
Upgrading to Rails 6 with the [latest version on RubyGems](https://rubygems.org/gems/rspec-sqlimit/versions/0.0.2) results in:
```
rspec-sqlimit was resolved to 0.0.2, which depends on
  rails (> 4.0, < 6.0)
```
It looks like [this](4f995f45d880fbe59ff7a1b07950304686fb121d) allows Rails 6 though, so cutting a new version including this should help those attempting to make the upgrade.

A workaround for anyone else encountering this issue would look like this:
```ruby
gem 'rspec-sqlimit', git: 'https://github.com/nepalez/rspec-sqlimit', ref: '0c62feb61710c93f20f086a427a7a14784e5ca0d'
```

**Comment by nepalez** [comment]
Thank you! Will fix it today

**Comment by Mayurifag** [comment]
So.. could you release the new version of gem, please?

**Comment by jaysonvirissimo** [comment]
@Mayurifag: drop that workaround (at the bottom of the first comment) into your `Gemfile` if you are on a tight deadline. I'm sure @nepalez is pretty busy like the rest of us.

**Comment by nepalez** [comment]
Sorry, guys. It took me time to make Travis pass.
And it still fails due to some problems in the latest commit; I need to fix it before the release.

**Comment by blackst0ne** [comment]
any update?

**Comment by Envek** [comment]
Release appeared on RubyGems today.
@nepalez, thank you for rspec-sqlimit!

**Comment by nepalez** [comment]
@Envek thank you for dropkicking me :)
sorry once again for such a looooooong delay
