### ISSUE TITLE
Depend on ActiveRecord and ActiveSupport only

### ISSUE THREAD

**Issue by miguelbernadi** [nepalez/rspec-sqlimit#17]
As far as I could see and understand from the blogpost, this doesn't need all of Rails to work, just Rspec, ActiveSupport and ActiveRecord. I have a project with ActiveRecord and ActiveSupport, but not the full Rails suite. Could it be changed in the gemspec for use cases like mine? I guess it should work fine either way, wouldn't it?

**Comment by miguelbernadi** [comment]
Bump

**Comment by nepalez** [comment]
Hi @miguelbernadi 
As far as I see, [a lot of tests failed](https://travis-ci.org/github/nepalez/rspec-sqlimit).
It seems like in the test environment we need more dependencies than a pure activerecord
Could you check it please?

**Comment by miguelbernadi** [comment]
@nepalez Sorry, I had not realized! Will check it out ASAP.
