### ISSUE TITLE
Release 0.0.2

### ISSUE THREAD

**Issue by cbliard** [nepalez/rspec-sqlimit#2]
Features described in the README like `.with(/^SELECT/)` or the nice error messages are not available in the published gem 0.0.1. Do you plan to release version 0.0.2?

**Comment by nepalez** [comment]
That is strange -- it should work.

Could you please tell me what this spec does return:
https://github.com/nepalez/rspec-sqlimit/blob/master/spec/rspec/sqlimit_spec.rb#L24

**Comment by cbliard** [comment]
The output is:
```
  1) exceed_query_limit with a restriction works when actual number of queries is below the limit
     Failure/Error: expect { User.create }.not_to exceed_query_limit(1).with(/INSERT/)
     
     NoMethodError:
       undefined method `with' for #<RSpec::Matchers::DSL::Matcher exceed_query_limit>
       Did you mean?  within
     # ./spec/casual_spec.rb:24:in `block (3 levels) in <top (required)>'
```

We are using rspec 3.4

**Comment by cbliard** [comment]
When it fails, it does not output the SQL requests either: if I make it fail with this:

```
it "works when actual number of queries is below the limit" do
  expect { User.create }.not_to exceed_query_limit(0)
end
```
Then I got this rspec output:
```
  1) exceed_query_limit with a restriction works when actual number of queries is below the limit
     Failure/Error: expect { User.create }.not_to exceed_query_limit(0)
       Expected to run maximum 0 queries, got 3
     # ./spec/casual_spec.rb:24:in `block (3 levels) in <top (required)>'
```

**Comment by nepalez** [comment]
Thank you! I'll take a look at it today and make a fix if necessary

**Comment by nepalez** [comment]
For now I cannot reproduce the behavior you've reported
(to be continued)

**Comment by cbliard** [comment]
I have tested with a new rails app and it indeed works as expected. I'll try to find what's wrong with our setup.

**Comment by nepalez** [comment]
Thank you for the feedback. Please, report here if you find something interesting ;)

**Comment by cbliard** [comment]
Found it: we copy-pasted a matcher more than 3 years ago from this [stackoverflow answer](https://stackoverflow.com/a/13423584/177665) and I totally forgot about it. It has the same signature but does a less more.

Sorry for the burden :expressionless:
