### ISSUE TITLE
Minitest support?

### ISSUE THREAD

**Issue by fatkodima** [nepalez/rspec-sqlimit#24]
Wdyt on supporting minitest?

I'm using kinda similar approach https://github.com/fatkodima/online_migrations/blob/10ad31af36d216affef56246679365279c60bb8d/test/support/minitest_helpers.rb#L41-L68 to track executed queries.

**Comment by nepalez** [comment]
Well, because I never use minitest, I don't feel enough expertise to support it.

But you're welcome with a PR :smile:

**Comment by fatkodima** [comment]
But you would need to change the gem name then 😄
